### ISSUE TITLE
Clarify license (GPLv2 vs GPLv3)

### ISSUE THREAD

**Issue by bkuhls** [kodi-adsp/adsp.biquad.filters#10]
Hi,

LICENSE.md is the text of the GPLv3, but the source files say GPLv2+.

Please clarify the license used for this package, thanks!

**Comment by AchimTuran** [comment]
@bkuhls 
Hi,

thanks for mention that issue. I will discuss this in our Team and then update them to GPLv3 or GPLv2.

**Comment by bkuhls** [comment]
Lost interest in this issue, closing...
