### ISSUE TITLE
Buildproblem building with gcc-6

### ISSUE THREAD

**Issue by sraue** [kodi-adsp/adsp.biquad.filters#13]
`
adsp.biquad.filters-af575f3/src/template/ADSPHelpers.cpp:27:29: error: 'float abs(float)' conflicts with a previous declaration
   inline float abs(float Val)
                             ^
`
and
`
adsp.biquad.filters-af575f3/src/template/ADSPHelpers.cpp:444:32: error: call of overloaded 'abs(float&)' is ambiguous
   return 20.0f*log10f(abs(Scale));
                                ^
`

**Comment by sraue** [comment]
thanks @bkuhls, works

**Comment by AchimTuran** [comment]
@sraue 

> thanks @bkuhls, works

Great then I will close this issue.

**Comment by sraue** [comment]
@AchimTuran it needs https://github.com/bkuhls/adsp.biquad.filters/commit/abae62ace5cd09025acaf8e03e5edad94131ff07 then it works (see the refernced comments and commits)
